# Generated by Django 5.2.7 on 2025-11-08 20:03

import core.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_deleted_at_file_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=core.models.drop_upload_path)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
